version: '3.8'
services:
  db:
    image: postgres:16
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME_ADD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ADD}
      - POSTGRES_USER=${POSTGRES_USER_ADD}
    ports:
      - '${DB_PORT1}:${DB_PORT2}'
    volumes:
      - ${DB_VOLUMES}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - '${APP_PORT1}:${APP_PORT1}'
    depends_on:
      - db

volumes:
  db_data: