version: '3.8'
services:
#  db:
#    image: postgres:16
#    container_name: db
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_USER=postgres
#    ports:
#      - '5433:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://l8o4kw8so84880wsko4wss04:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=PB84vtruCikHEBjMduWTS1Rb7wErsAmqIAMGo4yBAgYZWlEDPXf5kJ6m4acvGrGC
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - '8081:8080'
#    depends_on:
#      - db