version: '3.8'
services:
  db:
    image: postgres:16
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME_ADD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ADD}
      - POSTGRES_USER=${POSTGRES_USER_ADD}
    ports:
      - '3000:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CHROME_VERSION: ${CHROME_VERSION:-140.0.7339.82} # При отсутствии аргумента используется дефолт из Dockerfile
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - '8081:8080'
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    tmpfs:
      - /tmp

volumes:
  db_data:
