-- Создание таблицы для фиксации попыток смены ФИО покупателя
CREATE TABLE tb_customer_name_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES tb_customers(id) ON DELETE CASCADE,
    old_name TEXT,
    new_name TEXT NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

-- Индекс по клиенту для ускорения выборок
CREATE INDEX IF NOT EXISTS idx_customer_name_events_customer_id
    ON tb_customer_name_events(customer_id);
