-- Журнал отправки уведомлений клиентам
CREATE TABLE tb_customer_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES tb_customers(id) ON DELETE CASCADE,
    parcel_id BIGINT NOT NULL REFERENCES tb_track_parcels(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL,
    notification_type VARCHAR(20) NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_customer_notifications_customer ON tb_customer_notifications (customer_id);
CREATE INDEX idx_customer_notifications_parcel ON tb_customer_notifications (parcel_id);
