CREATE TABLE tb_store_telegram_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL UNIQUE REFERENCES tb_stores(id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    reminder_start_after_days SMALLINT NOT NULL DEFAULT 3,
    reminder_repeat_interval_days SMALLINT NOT NULL DEFAULT 2,
    custom_signature VARCHAR(200)
);

CREATE INDEX idx_store_telegram_settings_store ON tb_store_telegram_settings(store_id);
