-- Создание таблиц административных уведомлений и строк их содержимого

CREATE TABLE tb_admin_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'INACTIVE',
    reset_requested BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE tb_admin_notification_lines (
    notification_id BIGINT NOT NULL,
    body_lines_order INTEGER NOT NULL,
    line TEXT NOT NULL,
    CONSTRAINT pk_admin_notification_lines PRIMARY KEY (notification_id, body_lines_order),
    CONSTRAINT fk_admin_notification_lines_notification
        FOREIGN KEY (notification_id)
        REFERENCES tb_admin_notifications(id)
        ON DELETE CASCADE
);
