-- Создание таблиц административных уведомлений и строк их содержимого

CREATE TABLE tb_admin_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'INACTIVE',
    reset_requested BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE tb_admin_notification_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES tb_admin_notifications(id) ON DELETE CASCADE,
    line TEXT NOT NULL
);

CREATE INDEX idx_admin_notification_lines_notification_id
    ON tb_admin_notification_lines(notification_id);
