CREATE TABLE tb_users (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          password VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE tb_track_parcels (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  tracking_number VARCHAR(255) NOT NULL UNIQUE,
                                  user_id BIGINT REFERENCES tb_users,
                                  status VARCHAR(255) NOT NULL,
                                  data VARCHAR(255) NOT NULL
);

CREATE TABLE login_attempt (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               attempts INTEGER NOT NULL,
                               last_modified TIMESTAMP(6),
                               user_id BIGINT UNIQUE REFERENCES tb_users
);

CREATE TABLE confirmation_token (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    confirmation_code VARCHAR(255),
                                    created_at TIMESTAMP(6),
                                    email VARCHAR(255)
);

CREATE TABLE password_reset_token (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      expiration_date TIMESTAMP(6) NOT NULL,
                                      token VARCHAR(255) NOT NULL UNIQUE,
                                      email VARCHAR(255) NOT NULL UNIQUE
);