CREATE TABLE tb_track_status_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_parcel_id BIGINT NOT NULL REFERENCES tb_track_parcels(id) ON DELETE CASCADE,
    event_time TIMESTAMPTZ NOT NULL,
    description VARCHAR(1000) NOT NULL
);

CREATE INDEX idx_track_status_events_parcel ON tb_track_status_events(track_parcel_id, event_time DESC);
