CREATE TABLE tb_store_telegram_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settings_id BIGINT NOT NULL REFERENCES tb_store_telegram_settings(id) ON DELETE CASCADE,
    status VARCHAR(30) NOT NULL,
    template TEXT NOT NULL,
    CONSTRAINT chk_template_status CHECK (status IN ('REGISTERED','IN_TRANSIT','WAITING','DELIVERED','RETURNED')),
    CONSTRAINT uq_settings_status UNIQUE (settings_id, status)
);

CREATE INDEX idx_telegram_templates_settings ON tb_store_telegram_templates(settings_id);
