CREATE TABLE tb_user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES tb_users(id) ON DELETE CASCADE,
    show_bulk_update_button BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_user_settings_user ON tb_user_settings(user_id);
