CREATE TABLE tb_customer_telegram_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES tb_customers(id) ON DELETE CASCADE,
    store_id BIGINT REFERENCES tb_stores(id) ON DELETE CASCADE,
    telegram_chat_id BIGINT NOT NULL,
    notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    telegram_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    linked_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_customer_telegram_links_customer ON tb_customer_telegram_links(customer_id);
CREATE INDEX idx_customer_telegram_links_store ON tb_customer_telegram_links(store_id);
CREATE INDEX idx_customer_telegram_links_chat ON tb_customer_telegram_links(telegram_chat_id);
