-- 1. Создаем новую таблицу подписок пользователей
CREATE TABLE tb_user_subscriptions
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL UNIQUE
        CONSTRAINT fk_user_subscription REFERENCES tb_users ON DELETE CASCADE,
    subscription_plan_id  BIGINT NOT NULL
        CONSTRAINT fk_subscription_plan REFERENCES subscription_plans ON DELETE CASCADE,
    subscription_end_date TIMESTAMP WITH TIME ZONE,
    update_count          INTEGER DEFAULT 0,
    reset_date            DATE
);

-- 2. Перенос данных из tb_users в tb_user_subscriptions
INSERT INTO tb_user_subscriptions (user_id, subscription_plan_id, subscription_end_date, update_count, reset_date)
SELECT id, subscription_plan_id, subscription_end_date, update_count, CURRENT_DATE
FROM tb_users
WHERE subscription_plan_id IS NOT NULL;

-- 3. Удаление старых полей из tb_users
ALTER TABLE tb_users
    DROP COLUMN subscription_plan_id,
    DROP COLUMN subscription_end_date,
    DROP COLUMN update_count,
    DROP COLUMN last_update_date;
