-- Создаём таблицу tb_delivery_history
CREATE TABLE tb_delivery_history (
                                     id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     track_parcel_id  BIGINT NOT NULL REFERENCES tb_track_parcels ON DELETE CASCADE,
                                     store_id         BIGINT NOT NULL REFERENCES tb_stores ON DELETE CASCADE,
                                     postal_service   VARCHAR(50) NOT NULL,  -- Почтовая служба ("BELPOST", "EVROPOST")
                                     send_date        TIMESTAMP,
                                     received_date    TIMESTAMP,
                                     returned_date    TIMESTAMP
);

-- Добавляем индексы для ускорения запросов
CREATE INDEX idx_delivery_history_store ON tb_delivery_history (store_id);
CREATE INDEX idx_delivery_history_track ON tb_delivery_history (track_parcel_id);

-- Удаляем больше не нужные поля из tb_track_parcels
ALTER TABLE tb_track_parcels
    DROP COLUMN send_date,
    DROP COLUMN received_date,
    DROP COLUMN returned_date;
