CREATE TABLE IF NOT EXISTS tb_postal_service_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES tb_stores(id) ON DELETE CASCADE,
    postal_service_type VARCHAR(50) NOT NULL,
    total_sent INT NOT NULL DEFAULT 0,
    total_delivered INT NOT NULL DEFAULT 0,
    total_returned INT NOT NULL DEFAULT 0,
    sum_delivery_days NUMERIC(12,2) NOT NULL DEFAULT 0.0,
    sum_pickup_days NUMERIC(12,2) NOT NULL DEFAULT 0.0,
    updated_at TIMESTAMP
);
ALTER TABLE tb_postal_service_statistics
    ADD CONSTRAINT uk_postal_stats_store_service UNIQUE (store_id, postal_service_type);

CREATE INDEX IF NOT EXISTS idx_postal_stats_store ON tb_postal_service_statistics(store_id);
