-- Создаём таблицу ежедневной статистики магазинов
CREATE TABLE IF NOT EXISTS tb_store_statistics_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES tb_stores(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    sent INT NOT NULL DEFAULT 0,
    delivered INT NOT NULL DEFAULT 0,
    returned INT NOT NULL DEFAULT 0,
    sum_delivery_days NUMERIC(12,2) NOT NULL DEFAULT 0.0,
    sum_pickup_days NUMERIC(12,2) NOT NULL DEFAULT 0.0,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_store_stats_daily_store_date
    ON tb_store_statistics_daily(store_id, date);

-- Создаём таблицу ежедневной статистики почтовых служб
CREATE TABLE IF NOT EXISTS tb_postal_service_statistics_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES tb_stores(id) ON DELETE CASCADE,
    postal_service_type VARCHAR(50) NOT NULL,
    date DATE NOT NULL,
    sent INT NOT NULL DEFAULT 0,
    delivered INT NOT NULL DEFAULT 0,
    returned INT NOT NULL DEFAULT 0,
    sum_delivery_days NUMERIC(12,2) NOT NULL DEFAULT 0.0,
    sum_pickup_days NUMERIC(12,2) NOT NULL DEFAULT 0.0,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_postal_service_stats_daily_store_service_date
    ON tb_postal_service_statistics_daily(store_id, postal_service_type, date);
